version: '3.1'

services:
  stockpulse:
    container_name: StockPulse
    build: "StockPulse"
    restart: always

  clientpulse:
    container_name: ClientPulse
    build: "ClientPulse"
    restart: always

  managerpulse:
    container_name: ManagerPulse
    build: "ManagerPulse"
    ports:
      - '2000:2000'
    depends_on:
      - stockpulse
      - clientpulse
      - managerpulse_db
    restart: always

  managerpulse_db:
    container_name: managerpulse_db
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    restart: always
    volumes:
      - ./managerpulse_db:/data/db
