version: '3.1'

services:
  stockpulse:
    container_name: StockPulse
    build: "StockPulse"
    environment:
      - MODE=development
    ports:
      - '8000:8000'
    depends_on:
      - stockpulse_db
    restart: always

  stockpulse_db:
    container_name: stockpulse_db
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=stockpulse
      - MYSQL_PASSWORD=123456
    restart: always
    volumes:
      - ./stockpulse_db:/var/lib/mysql

  clientpulse:
    container_name: ClientPulse
    build: "ClientPulse"
    environment:
      - MODE=development
    ports:
      - '3000:3000'
    depends_on:
      - stockpulse
      - clientpulse_db
    restart: always

  clientpulse_db:
    container_name: clientpulse_db
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=clientpulse
      - MYSQL_PASSWORD=123456
    restart: always
    volumes:
      - ./clientpulse_db:/var/lib/mysql

  managerpulse:
    container_name: ManagerPulse
    build: "ManagerPulse"
    ports:
      - '2000:2000'
    environment:
      - MODE=development
    depends_on:
      - stockpulse
      - clientpulse
      - managerpulse_db
    restart: always

  managerpulse_db:
    container_name: managerpulse_db
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./managerpulse_db:/data/db

  managerpulse_db_express:
    container_name: managerpulse_db_express
    image: "mongo-express:latest"
    env_file:
      - ./ManagerPulse/.env
    depends_on:
      - managerpulse_db
    restart: always
