version: '3.1'

services:
  stockpulse:
    container_name: StockPulse
    build: "https://github.com/certainlyWrong/StockPulse.git"
    env_file:
      - .env_stock
    restart: always

  clientpulse:
    container_name: ClientPulse
    build: "https://github.com/certainlyWrong/ClientPulse.git"
    env_file:
      - .env_client
    depends_on:
      - stockpulse
    restart: always

  managerpulse:
    container_name: ManagerPulse
    build: "https://github.com/certainlyWrong/ManagerPulse.git"
    env_file:
      - .env_manager
    ports:
      - '2000:2000'
    depends_on:
      - stockpulse
      - clientpulse
      - managerpulse_db
    restart: always

  managerpulse_db:
    container_name: managerpulse_db
    image: "mongo:latest"
    env_file:
      - .env_manager
    restart: always
    volumes:
      - ./managerpulse_db:/data/db

  managerpulse_db_express:
    container_name: managerpulse_db_express
    image: "mongo-express:latest"
    env_file:
      - .env_manager
    ports:
      - '8081'
    depends_on:
      - managerpulse_db
    restart: always
